49484 Added wb-update-notifier code
wirenboard/wb-update-notifier pull request #1
Opened 2022-06-29 10:46 UTC by rkochkin

Добавил новый репозиторий и генерацию deb пакета.

Вносит настройку регулярного выполнения atp update. 
Настроен хук при котором после выполнения atp update  выполненяется оценка того, сколько пакетов не обновлено.
Количество пакетов пишется в файл-штамп.
В баннере в консоли WB, пользователю выдаётся содержимое файл-штампа: сколько пакетов можно обновить и как это сделать.

2022-06-29 11:07 UTC, rkochkin commented
Баннер выглядит вот так:

![Screenshot_20220629_140604](https://user-images.githubusercontent.com/12100943/176422338-b66db4af-2299-4303-b2a5-3dbcd2807b19.png)

2022-06-29 11:10 UTC, webconn requested changes
А структура директорий/файлов в пакете скопирована из убунты? Мне не очень нравится класть что-то полезное связанное с пакетом в `debian/`.

Думал ещё, что это всё можно перетащить в wb-configs, но с другой стороны, сюда потом можно добавить скрипты вокруг прошивок, например, и уведомления о новых релизах

2022-06-29 11:10 UTC, webconn commented on Jenkinsfile
> +buildDebSbuild defaultTargets: 'wb6',
Тут лучше использовать пайплайн `buildDebArchAll()`, он чуть лучше подходит для пакетов без архитектурных зависимостей

2022-06-29 11:10 UTC, webconn commented on debian/control
> +Build-Depends: debhelper (>= 10)
Добавь ещё сюда Homepage с адресом репозитория на гитхабе (https)

2022-06-29 11:10 UTC, webconn commented on debian/rules
> +override_dh_installinit:
Эта секция не нужна же, тут нет инитскрипта, тем более что от init.d мы усиленно отказываемся

2022-06-29 11:10 UTC, webconn commented on debian/control
> +Breaks:
Пустая секция, тоже можно не писать. А вот apt в depends прописать бы неплохо

2022-06-29 11:10 UTC, webconn commented on debian/changelog
> +  * Initial release
Напиши тут сразу, что поддерживает уведомления о новых пакетах в apt

2022-06-29 12:03 UTC, rkochkin commented on debian/control
> +Build-Depends: debhelper (>= 10)
Сделал

2022-06-29 12:03 UTC, rkochkin commented on debian/rules
> +override_dh_installinit:
Убрал

2022-06-29 12:03 UTC, rkochkin commented on debian/control
> +Breaks:
Сделал

2022-06-29 12:03 UTC, rkochkin commented on debian/changelog
> +  * Initial release
Написал

2022-06-29 12:15 UTC, rkochkin commented on Jenkinsfile
> +buildDebSbuild defaultTargets: 'wb6',
Поправил

2022-06-29 13:46 UTC, rkochkin commented
> А структура директорий/файлов в пакете скопирована из убунты? Мне не очень нравится класть что-то полезное связанное с пакетом в `debian/`.
> 
> Думал ещё, что это всё можно перетащить в wb-configs, но с другой стороны, сюда потом можно добавить скрипты вокруг прошивок, например, и уведомления о новых релизах

Структура директории /debian как в пакете update-notifier. @webconn В итоге переложить  скрипты и конфиги в корневую директорию проекта?

2022-06-29 13:48 UTC, webconn commented
> Структура директории /debian как в пакете update-notifier. @webconn В итоге переложить  скрипты и конфиги в корневую директорию проекта?

Не, можно не переносить, но в ридми написать, что часть про арт списана с убунты (и указать версию пакета, с которой списывал)

2022-06-29 13:58 UTC, rkochkin commented
> > Структура директории /debian как в пакете update-notifier. @webconn В итоге переложить  скрипты и конфиги в корневую директорию проекта?
> 
> Не, можно не переносить, но в ридми написать, что часть про apt списана с убунты (и указать версию пакета, с которой списывал)

Сделал

2022-06-30 07:22 UTC, webconn requested changes

2022-06-30 07:22 UTC, webconn commented on debian/control
> +Architecture: any
Ещё заметил, тут же пакет, в котором нет ничего архитектурно-зависимого, потому здесь должно быть `all`, а не `any`. Из-за `any` после сборки получился пакет для amd64 :)

2022-07-01 07:21 UTC, rkochkin commented on debian/control
> +Architecture: any
Поправил

2022-07-01 11:59 UTC, webconn approved these changes
Вывод сообщения работает, только осталось проверить, что apt сам себе списки пакетов периодически обновляет.

Надо будет добавить этот пакет в Recommeds в wb-suite (репозиторий wirenboard/wb-metapackages)

2022-07-13 06:34 UTC, rkochkin commented
> Вывод сообщения работает, только осталось проверить, что apt сам себе списки пакетов периодически обновляет.
> 
> Надо будет добавить этот пакет в Recommeds в wb-suite (репозиторий wirenboard/wb-metapackages)

Запустил cron.daily. По этому триггеру запустился apt update и скрипт, вычисляющий сколько пакетов нужно обновить.
@webconn Думаю можно заливать в мастер.

2022-07-13 06:55 UTC, merged